version: 1
disable_existing_loggers: False
formatters:
    formatter:
        format: "%(asctime)s - %(levelname)-8s - %(name)s:%(lineno)d |> %(message)s"
        datefmt: "%d.%m.%Y %H:%M:%S"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: formatter
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: formatter
        filename: Log/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 200
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: formatter
        filename: Log/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, debug_file_handler, error_file_handler]
